AllCops:
  RunRailsCops: true
  Exclude:
   - "bin/**/*"
   - "db/migrate/**/*"
   - "db/schema.rb"
   - "vendor/**/*"
   - "gemfiles/vendor/**/*"

Metrics/LineLength:
  Max: 90

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 17