Rails:
  enabled: true

AllCops:
  Exclude:
   - "bin/**/*"
   - "db/migrate/**/*"
   - "db/schema.rb"
   - "vendor/**/*"
   - "gemfiles/vendor/**/*"

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 17

Documentation:
  Enabled: false
