language: ruby
cache: bundler
bundler_args: "--without production"
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
notifications:
  slack:
    secure: OixL+deBxFfKx8ORQSIOufPzcMfsoGN572D4MMDuV7qWLFEHQ33WWR+6pbTyTaYn5XtA4tWxD0QtCy3pZbHBS/M9bJjMzOF1wq8aIk63cgL/SZfFrqorQeGc5iaKPce3BK2x+LUES06pQsRR8N3PpXnCO/pAqqCmaO9vjQHW+86aLK4GJxDZqzj7d96/3rP9CWSoM/gYTWmXUR3riDofcAky8QId1wR6nNMk6Nrgw0iHgzRC5s2fvg72KetWI7Dt7oDKsMwMCjy7pk0gIAWNqpapKhYLrwWvrvaCrgbcW8R40J7Uq4jvgrhZGGBVS7IaQz+7gCRgRPRZl8l+6r0PYWv2ETw1gmyn7oA/C7UUD37jAJhCIYg256YM8zjh2WR79Kfvz20jBnjlArjIZzM/KHF6G0UBvwn+JBhL1Z54BKgVMZiKKdnqtGoJPmJw9PslNX3NEZVrFsYtgzb434hcRyixJtp2mTAVrW01jt7bzz/RUlGkIvwepjwyVxTWHCyJp2rRHqmRP7R6sSUTa9qYHXL9FGDK5sa7TYLNjPdxtSicLpDlBIDic3wrOrcaKKpWgIphC8Rw2nLxFU3rvLDUCihi8quOvrIAL/RW7FY0HcUycu8LiNm2DNuHF2rXihUYrakLUdC6TgibtIWySTq1cjJPMg1djOdS+Q8AXnm5UGE=
