development:
    host: localhost
    database: plan_characters_dev

test:
    host: MONGOHQ_URL
    database: plan_characters_test

production:
    host: MONGOHQ_URL
    database: plan_characters_prod
