development:
  host: localhost
  database: plan_characters_dev

test:
  sessions:
    default:
      database: myapp_test
      hosts:
        - localhost:27017

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
