development:
  sessions:
    default:
      database: plan_characters_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: myapp_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
