development:
  host: localhost
  database: plan_characters_dev

test:
  sessions:
    default:
      database: myapp_test
      host: localhost
      port: 27017

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
