:general:
  :label: General
  :icon: info
  :attributes:
    - :name: entity_type
      :label: Entity Type
    - :name: name
      :label: Name
    - :name: label
      :label: Label
    - :name: icon
      :label: Icon
