:general:
  :label: General
  :icon: info
  :attributes:
    - :name: label
      :label: Label
    - :name: field_type
      :label: Field Type
    - :name: attribute_category_id
      :label: Attribute Category
    - :name: name
      :label: Name
    - :name: description
      :label: Description
