:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: other_names
      :label: Other names
    - :name: universe_id
      :label: Universe
:culture:
  :label: Culture
  :icon: face
  :attributes:
    - :name: laws
      :label: Laws
    - :name: sports
      :label: Sports
    - :name: politics
      :label: Politics
:history:
  :label: History
  :icon: fingerprint
  :attributes:
    - :name: founding_story
      :label: Founding story
    - :name: established_year
      :label: Established year
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
