:overview:
  :label: overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
:history:
  :label: History
  :icon: book
  :attributes:
    - :name: history
      :label: History
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
:settings:
  :label: Settings
  :icon: build
  :attributes:
    - :name: privacy
      :label: Privacy
